# Generated by Django 2.2 on 2021-06-09 18:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrequestsetting',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='analysisrequestsetting',
            name='analysis_features',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
