# Generated by Django 2.2 on 2021-06-09 18:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_request', '0002_auto_20210609_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='analysis_request',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
