# Generated by Django 2.2 on 2021-07-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_request', '0004_analysisrequestsolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequestsolution',
            name='analysis_request_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='analysisrequestsolution',
            name='solution_master_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
