# Generated by Django 2.2 on 2021-07-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_request', '0005_auto_20210727_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisrequestsolution',
            name='solution_list',
        ),
        migrations.AddField(
            model_name='analysisrequestsolution',
            name='solution_text',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
