# Generated by Django 2.2 on 2022-04-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_request', '0006_auto_20210728_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequestsolution',
            name='solution_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
