# Generated by Django 2.2 on 2020-07-01 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0002_classificationdetails_classification_training_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationdetails',
            name='classification_training_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.TrainingDetails'),
        ),
    ]
