# Generated by Django 2.2 on 2020-07-01 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0005_auto_20200701_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationdetails',
            name='classification_training_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.TrainingDetails'),
        ),
    ]
