# Generated by Django 2.2 on 2022-04-28 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0006_auto_20200701_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationdetails',
            name='classification_training_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='training.TrainingDetails'),
            preserve_default=False,
        ),
    ]
