# Generated by Django 2.2 on 2020-07-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20200507_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdetails',
            name='training_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
