# Generated by Django 2.2 on 2020-07-14 10:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_trainingdetails_training_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdetails',
            name='nlp_training_id',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ModelDetails',
            fields=[
                ('model_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('nlp_model_id', models.IntegerField(default=0)),
                ('algorithm_id', models.IntegerField(default=0)),
                ('algorithm_name', models.CharField(blank=True, max_length=255, null=True)),
                ('algorithm_config', models.TextField(blank=True, null=True)),
                ('accuracy', models.FloatField(default=0)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_date_time', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('classification_training_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.TrainingDetails')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.StatusmasterDetails')),
            ],
            options={
                'db_table': 'model_details',
            },
        ),
    ]
