# Generated by Django 2.2 on 2020-07-27 13:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_auto_20200714_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingdetails',
            name='file_id',
        ),
        migrations.AddField(
            model_name='trainingdetails',
            name='file',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TextMasterHistory',
            fields=[
                ('text_history_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('client_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('status_id', models.IntegerField()),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_date_time', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('file_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.FileDetails')),
            ],
            options={
                'db_table': 'text_master_history',
            },
        ),
    ]
