# Generated by Django 2.2 on 2020-08-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20200727_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldetails',
            name='is_default',
            field=models.IntegerField(default=1),
        ),
    ]
