# Generated by Django 2.2 on 2021-06-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_modeldetails_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationmasterdetails',
            name='request_type',
            field=models.CharField(default='Classification', max_length=350),
        ),
    ]
