# Generated by Django 2.2 on 2021-06-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_auto_20210601_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmasterdetails',
            name='classification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textmasterdetails',
            name='entities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textmasterdetails',
            name='intent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
