# Generated by Django 2.2 on 2021-06-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_auto_20210610_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmasterdetails',
            name='text_reference_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textmasterhistory',
            name='text_reference_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
