# Generated by Django 2.2 on 2021-06-13 20:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_auto_20210611_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdetails',
            name='classification_model',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingdetails',
            name='intent_model',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
