# Generated by Django 2.2 on 2021-07-14 11:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_auto_20210613_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmasterdetails',
            name='hierarchy',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
