# Generated by Django 2.2 on 2022-04-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_textmasterdetails_solution_mapping_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmasterdetails',
            name='sentiment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
