# Generated by Django 2.2 on 2022-05-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_textmasterdetails_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmasterdetails',
            name='predictive',
            field=models.TextField(blank=True, null=True),
        ),
    ]
